# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  changed_files:    
    runs-on: ubuntu-latest
    name: Testing Changes
    steps:
      - uses: actions/checkout@v4

      - name: Get Changed files
        id: changed-files
        uses: tj-actions/changed-files@v43

      - name: Grid Only
        uses: tj-actions/changed-files@v43
        id: grid-only
        with:
          files_yaml: |
            src:
              - www/**
              - lib/**

      - name: Grid Only
        uses: tj-actions/changed-files@v43
        id: mhws-only
        with:
          files_yaml: |
            src:
              - mhws/**
              - lib/**
      
      - name: Run Step if grid changes
        if: steps.grid-only.outputs.test_any_changed == 'true'
        env:
          GRID_CHANGED_FILES: ${{ steps.grid-only.outputs.all_changed_files }}
        run: |
          echo "********************************"
          echo "Grid files changes"
          for file in ${GRID_CHANGED_FILES}; do
            echo "$file was changed"
          done
          echo "********************************"


      - name: Run Step if grid changes
        if: steps.grid-only.outputs.test_any_changed == 'true'
        env:
          MHWS_CHANGED_FILES: ${{ steps.mhws-only.outputs.all_changed_files }}
        run: |
            echo "********************************"
            echo "MHWS files changes"
            for file in ${MHWS_CHANGED_FILES}; do
              echo "$file was changed"
            done
            echo "********************************"
  

#   build:

#     runs-on: ubuntu-latest

#     steps:
#     - uses: actions/checkout@v4
#     - name: Setup .NET
#       uses: actions/setup-dotnet@v4
#       with:
#         dotnet-version: 8.0.x
#     - name: Restore dependencies
#       run: dotnet restore
#     - name: Build
#       run: dotnet build --no-restore
# #    - name: Test
# #      run: dotnet test --no-build --verbosity normal
